import { expect, test } from '@playwright/test';

test('Nosotros guarda y publica perfiles sin filtrar borradores; navegación desktop y mobile', async ({ page, request }, info) => {
  const name = `Integrante ${info.project.name}`;
  await page.goto('/gestion');
  await page.getByRole('button', { name: 'Nosotros', exact: true }).click();
  const manager = page.getByRole('region', { name: 'Gestión de Nosotros' });
  await manager.getByLabel('Nombre completo').fill(name);
  await manager.getByLabel('Función en Quórum').fill('Coordinación editorial');
  await manager.getByLabel('Área o equipo de la organización').fill('Investigación');
  await manager.getByLabel('Presentación del integrante').fill('Trabajamos para acercar la actividad legislativa a la ciudadanía.');
  await manager.getByRole('button', { name: 'Guardar borrador', exact: true }).click();
  await expect(manager.getByRole('status')).toContainText('Borrador guardado');
  await page.reload();
  await page.getByRole('button', { name: 'Nosotros', exact: true }).click();
  await manager.getByRole('button', { name: `${name} · Borrador`, exact: true }).click();
  await expect(manager.getByLabel('Área o equipo de la organización')).toHaveValue('Investigación');
  const publicPage = await page.context().newPage();
  await publicPage.goto('/nosotros');
  await expect(publicPage.getByRole('heading', { name, exact: true })).toHaveCount(0);
  page.once('dialog', dialog => dialog.accept());
  await manager.getByRole('button', { name: 'Guardar y publicar', exact: true }).click();
  await expect(manager.getByRole('status')).toContainText('Perfil publicado');
  await publicPage.reload();
  await expect(publicPage.getByRole('heading', { name, exact: true })).toBeVisible();
  await expect(publicPage.getByRole('link', { name: 'Nosotros', exact: true }).first()).toBeAttached();
  if ((page.viewportSize()?.width || 1280) < 860) await expect(publicPage.getByRole('navigation', { name: 'Navegación móvil de Quórum' }).getByRole('link', { name: 'Nosotros', exact: true })).toBeVisible();
  expect(await publicPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await publicPage.screenshot({ path: info.outputPath('nosotros.png'), fullPage: true });
  await manager.getByLabel('Nombre completo').fill(name + ' editado');
  await manager.getByRole('button', { name: 'Guardar borrador', exact: true }).click();
  await expect(manager.getByRole('status')).toContainText('Borrador guardado');
  await publicPage.reload();
  await expect(publicPage.getByRole('heading', { name, exact: true })).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await manager.getByRole('button', { name: 'Guardar y publicar', exact: true }).click();
  await expect(manager.getByRole('status')).toContainText('Perfil publicado');
  await publicPage.reload();
  await expect(publicPage.getByRole('heading', { name: name + ' editado', exact: true })).toBeVisible();
  // Network failure must retain local edits.
  await manager.getByLabel('Presentación del integrante').fill('Texto que no se debe perder ante un fallo.');
  await page.route('**/v1/manage/team/*', route => route.request().method() === 'PUT' ? route.fulfill({ status: 500, json: { error: { message: 'Fallo de prueba' } } }) : route.continue());
  await manager.getByRole('button', { name: 'Guardar borrador', exact: true }).click();
  await expect(manager.getByRole('alert')).toContainText('Fallo de prueba');
  await expect(manager.getByLabel('Presentación del integrante')).toHaveValue('Texto que no se debe perder ante un fallo.');
  await page.unroute('**/v1/manage/team/*');
  page.once('dialog', dialog => dialog.accept());
  await manager.getByRole('button', { name: 'Despublicar', exact: true }).click();
  await expect(manager.getByRole('status')).toContainText('Perfil despublicado');
  await publicPage.reload();
  await expect(publicPage.getByRole('heading', { name: name + ' editado', exact: true })).toHaveCount(0);
  await publicPage.close();
});
