substitutions:
  _REGION: southamerica-east1
  _REPOSITORY: quorum
  _IMAGE_TAG: manual
steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "services/quorum-api/Dockerfile", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/quorum-api:${_IMAGE_TAG}", "."]
images: ["${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/quorum-api:${_IMAGE_TAG}"]
