substitutions:
  _REGION: southamerica-east1
  _REPOSITORY: quorum
  _SERVICE: quorum-api-staging
steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "services/quorum-api/Dockerfile", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/quorum-api:$COMMIT_SHA", "."]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: ["run", "deploy", "${_SERVICE}", "--image", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/quorum-api:$COMMIT_SHA", "--region", "${_REGION}", "--quiet"]
images: ["${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/quorum-api:$COMMIT_SHA"]
